
RegExp.escape=function(s){return s.replace(/[-\/\\^$*+?.()|[\]{}]/g,'\\$&');};(function($){'use strict'
$.csv={defaults:{separator:',',delimiter:'"',escaper:'"',skip:0,headerLine:1,dataLine:2},configure:function(options){var defaults=$.extend({__copy:true},$.csv.defaults);return $.extend(defaults,options);},splitLines:function(csv,delimiter){var state=0;var value="";var line="";var lines=[];function endOfRow(){lines.push(value);value="";state=0;};csv.replace(/(\"|\n|\r|[^\"\r\n]+)/gm,function(m0){switch(state){case 0:if(m0==="\""){state=1;}else if(m0==="\n"){endOfRow();}else if(/^\r$/.test(m0)){}else{if(value){throw new Error("Illegal initial state");}
value=m0;state=3;}
break;case 1:if(m0==="\""){state=2;}else if((m0==="\n")||(m0==="\r")){value+=m0;state=1;}else{value+=m0;state=1;}
break;case 2:if(m0==="\""&&value.substr(value.length-1)==="\""){value+=m0;state=1;}else if(m0===","){value+=m0;state=0;}else if(m0==="\n"){endOfRow();}else if(m0==="\r"){}else{throw new Error("Illegal state");}
break;case 3:if(m1==="\""){throw new Error("Unquoted delimiter found in string");}else if(m0==="\n"){endOfRow();}else if(m0==="\r"){}else{throw new Error("Two values, no separator?");}
break;default:throw new Error("Unknown state");}
return"";});if(state!=0){endOfRow();}
return lines;},toArray:function(csv,options){var options=(options!==undefined?options:{});var separator='separator'in options?options.separator:$.csv.defaults.separator;var delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;var escaper='escaper'in options?options.escaper:$.csv.defaults.escaper;separator=RegExp.escape(separator);delimiter=RegExp.escape(delimiter);escaper=RegExp.escape(escaper);var reValue=/(?!\s*$)\s*(?:Y([^YZ]*(?:ZY[^YZ]*)*)Y|([^XYZ\s]*(?:\s+[^XYZ\s]+)*))\s*(?:X|$)/;var reValueSrc=reValue.source;reValueSrc=reValueSrc.replace(/X/g,separator);reValueSrc=reValueSrc.replace(/Y/g,delimiter);reValueSrc=reValueSrc.replace(/Z/g,escaper);reValue=RegExp(reValueSrc,'g');if(csv===""){return[""];}
var output=[];csv.replace(reValue,function(m0,m1,m2){if(typeof m1==='string'&&m1.length){var reDelimiterUnescape=/ED/;var reDelimiterUnescapeSrc=reDelimiterUnescape.source;reDelimiterUnescapeSrc=reDelimiterUnescapeSrc.replace(/E/,escaper);reDelimiterUnescapeSrc=reDelimiterUnescapeSrc.replace(/D/,delimiter);reDelimiterUnescape=RegExp(reDelimiterUnescapeSrc,'g');output.push(m1.replace(reDelimiterUnescape,delimiter));}else if(m2!==undefined){output.push(m2);}
return'';});var reEmptyLast=/S\s*$/;reEmptyLast=RegExp(reEmptyLast.source.replace(/S/,separator));if(reEmptyLast.test(csv)){output.push('');}
return output;},toArrays:function(csv,options){var options=(options!==undefined?options:{});var separator='separator'in options?options.separator:$.csv.defaults.separator;var delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;var escaper='escaper'in options?options.escaper:$.csv.defaults.escaper;var skip='skip'in options?options.skip:$.csv.defaults.skip;var experimental='experimental'in options?options.experimental:false;var lines=[];var output=[];if(!experimental){lines=csv.split(/\r\n|\r|\n/g);}else{lines=$.csv.splitLines(csv,delimiter);}
for(var i in lines){if(i<skip){continue;}
var entry=$.csvEntry2Array(lines[i],{delimiter:delimiter,separator:separator,escaper:escaper});output.push(entry);}
return output;},toObjects:function(csv,options){var options=(options!==undefined?options:{});var separator='separator'in options?options.separator:$.csv.defaults.separator;var delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;var escaper='escaper'in options?options.escaper:$.csv.defaults.escaper;var headerLine='headerLine'in options?options.headerLine:$.csv.defaults.headerLine;var dataLine='dataLine'in options?options.dataLine:$.csv.defaults.dataLine;var experimental='experimental'in options?options.experimental:false;var lines=[];var output=[];if(!experimental){lines=csv.split(/\r\n|\r|\n/g);}else{lines=this.splitLines(csv,delimiter);}
var headers=$.csvEntry2Array(lines[(headerLine-1)]);for(var i in lines){if(i<(dataLine-1)){continue;}
var entry=$.csvEntry2Array(lines[i],{delimiter:delimiter,separator:separator,escaper:escaper});var object={};for(var j in headers){object[headers[j]]=entry[j];}
output.push(object);}
return output;},fromArrays:function(arrays,options){var options=(options!==undefined?options:{});var separator='separator'in options?options.separator:$.csv.defaults.separator;var delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;var escaper='escaper'in options?options.escaper:$.csv.defaults.escaper;var experimental='experimental'in options?options.experimental:false;if(!experimental){throw new Error("not implemented");}
var output=[];for(i in arrays){output.push(arrays[i]);}
return output;},fromObjects2CSV:function(objects,options){var separator='separator'in options?options.separator:$.csv.defaults.separator;var delimiter='delimiter'in options?options.delimiter:$.csv.defaults.delimiter;var escaper='escaper'in options?options.escaper:$.csv.defaults.escaper;var experimental='experimental'in options?options.experimental:false;if(!experimental){throw new Error("not implemented");}
var output=[];for(i in objects){output.push(arrays[i]);}
return output;}};$.csvEntry2Array=$.csv.toArray;$.csv2Array=$.csv.toArrays;$.csv2Dictionary=$.csv.toObjects;})(jQuery);